//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the MRC_DataBaseData datasource.
    /// </summary>
    public sealed partial class MRC_DataBaseDataService
        : global::LightSwitchApplication.MRC_DataBaseData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public MRC_DataBaseDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_Inserting(global::LightSwitchApplication.JobCard entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_Inserted(global::LightSwitchApplication.JobCard entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_Updating(global::LightSwitchApplication.JobCard entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_Updated(global::LightSwitchApplication.JobCard entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_Deleting(global::LightSwitchApplication.JobCard entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_Deleted(global::LightSwitchApplication.JobCard entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_Validate(global::LightSwitchApplication.JobCard entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.JobCard, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.MRC_DataBaseDataService, global::LightSwitchApplication.JobCard>
                __JobCardsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.MRC_DataBaseDataService, global::LightSwitchApplication.JobCard>(
                    "JobCards",
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__JobCards_CanInsert,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__JobCards_CanUpdate,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__JobCards_CanDelete,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__JobCards_CanRead,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__JobCards_Inserting,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__JobCards_Inserted,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__JobCards_Updating,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__JobCards_Updated,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__JobCards_Deleting,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__JobCards_Deleted,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__JobCards_Validate,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__JobCards_Filter);
            private static bool __JobCards_CanInsert(global::LightSwitchApplication.MRC_DataBaseDataService d)
            {
                bool result = true;
                d.JobCards_CanInsert(ref result);
                return result;
            }
            private static bool __JobCards_CanUpdate(global::LightSwitchApplication.MRC_DataBaseDataService d)
            {
                bool result = true;
                d.JobCards_CanUpdate(ref result);
                return result;
            }
            private static bool __JobCards_CanDelete(global::LightSwitchApplication.MRC_DataBaseDataService d)
            {
                bool result = true;
                d.JobCards_CanDelete(ref result);
                return result;
            }
            private static bool __JobCards_CanRead(global::LightSwitchApplication.MRC_DataBaseDataService d)
            {
                bool result = true;
                d.JobCards_CanRead(ref result);
                return result;
            }
            private static void __JobCards_Inserting(global::LightSwitchApplication.MRC_DataBaseDataService d, global::LightSwitchApplication.JobCard e)
            {
                d.JobCards_Inserting(e);
            }
            private static void __JobCards_Inserted(global::LightSwitchApplication.MRC_DataBaseDataService d, global::LightSwitchApplication.JobCard e)
            {
                d.JobCards_Inserted(e);
            }
            private static void __JobCards_Updating(global::LightSwitchApplication.MRC_DataBaseDataService d, global::LightSwitchApplication.JobCard e)
            {
                d.JobCards_Updating(e);
            }
            private static void __JobCards_Updated(global::LightSwitchApplication.MRC_DataBaseDataService d, global::LightSwitchApplication.JobCard e)
            {
                d.JobCards_Updated(e);
            }
            private static void __JobCards_Deleting(global::LightSwitchApplication.MRC_DataBaseDataService d, global::LightSwitchApplication.JobCard e)
            {
                d.JobCards_Deleting(e);
            }
            private static void __JobCards_Deleted(global::LightSwitchApplication.MRC_DataBaseDataService d, global::LightSwitchApplication.JobCard e)
            {
                d.JobCards_Deleted(e);
            }
            private static void __JobCards_Validate(global::LightSwitchApplication.MRC_DataBaseDataService d, global::LightSwitchApplication.JobCard e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.JobCards_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.JobCard, bool>> __JobCards_Filter(global::LightSwitchApplication.MRC_DataBaseDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.JobCard, bool>> filter = null;
                d.JobCards_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.MRC_DataBaseDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.MRC_DataBaseDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.MRC_DataBaseDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.MRC_DataBaseDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.MRC_DataBaseDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.MRC_DataBaseDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.MRC_DataBaseDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.MRC_DataBaseDataService>(
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.MRC_DataBaseDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.MRC_DataBaseDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.MRC_DataBaseDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.MRC_DataBaseDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
        }
    
        #endregion
    }
    
    #endregion
}
