//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 12/2/2016 9:19:47 PM
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for MRC_DataBaseData in the schema.
    /// </summary>
    public partial class MRC_DataBaseData : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new MRC_DataBaseData object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MRC_DataBaseData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication", "LightSwitchApplication.Implementation");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for JobCards in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<JobCard> JobCards
        {
            get
            {
                if ((this._JobCards == null))
                {
                    this._JobCards = base.CreateQuery<JobCard>("JobCards");
                }
                return this._JobCards;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<JobCard> _JobCards;
        /// <summary>
        /// There are no comments for JobCards in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToJobCards(JobCard jobCard)
        {
            base.AddObject("JobCards", jobCard);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"JobCard\"><Key><PropertyRef Name=\"JID\" /></Key>" +
                "<Property Name=\"JID\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGenerated" +
                "Pattern=\"Identity\" /><Property Name=\"JobNumber\" Type=\"Edm.String\" MaxLength=\"Max" +
                "\" Unicode=\"false\" /><Property Name=\"JName\" Type=\"Edm.String\" MaxLength=\"Max\" Uni" +
                "code=\"false\" /><Property Name=\"BuildingOwner\" Type=\"Edm.String\" MaxLength=\"Max\" " +
                "Unicode=\"false\" /><Property Name=\"GeneralContractor\" Type=\"Edm.String\" MaxLength" +
                "=\"Max\" Unicode=\"false\" /><Property Name=\"JDescription\" Type=\"Edm.String\" MaxLeng" +
                "th=\"Max\" Unicode=\"false\" /><Property Name=\"JHoursEstmated\" Type=\"Edm.Decimal\" Pr" +
                "ecision=\"18\" Scale=\"0\" ConcurrencyMode=\"Fixed\" /><Property Name=\"JHoursTook\" Typ" +
                "e=\"Edm.Decimal\" Precision=\"18\" Scale=\"0\" ConcurrencyMode=\"Fixed\" /><Property Nam" +
                "e=\"JPrice\" Type=\"Edm.Decimal\" Precision=\"19\" Scale=\"4\" ConcurrencyMode=\"Fixed\" /" +
                "><Property Name=\"JSquares\" Type=\"Edm.Decimal\" Precision=\"18\" Scale=\"0\" Concurren" +
                "cyMode=\"Fixed\" /><Property Name=\"JDate\" Type=\"Edm.DateTime\" Precision=\"0\" Concur" +
                "rencyMode=\"Fixed\" /><Property Name=\"JWarrenty\" Type=\"Edm.String\" MaxLength=\"Max\"" +
                " Unicode=\"false\" /><Property Name=\"WarrantyNumber\" Type=\"Edm.String\" MaxLength=\"" +
                "Max\" Unicode=\"false\" /><Property Name=\"WarrantyStart\" Type=\"Edm.DateTime\" Precis" +
                "ion=\"0\" ConcurrencyMode=\"Fixed\" /><Property Name=\"WarrantyEnd\" Type=\"Edm.DateTim" +
                "e\" Precision=\"0\" ConcurrencyMode=\"Fixed\" /><Property Name=\"Address1\" Type=\"Edm.S" +
                "tring\" MaxLength=\"Max\" Unicode=\"false\" /><Property Name=\"Address2\" Type=\"Edm.Str" +
                "ing\" MaxLength=\"Max\" Unicode=\"false\" /><Property Name=\"City\" Type=\"Edm.String\" M" +
                "axLength=\"Max\" Unicode=\"false\" /><Property Name=\"State\" Type=\"Edm.String\" MaxLen" +
                "gth=\"10\" FixedLength=\"true\" ConcurrencyMode=\"Fixed\" /><Property Name=\"Zip\" Type=" +
                "\"Edm.String\" MaxLength=\"10\" FixedLength=\"true\" ConcurrencyMode=\"Fixed\" /></Entit" +
                "yType><EntityContainer Name=\"MRC_DataBaseData\" m:IsDefaultEntityContainer=\"true\"" +
                "><EntitySet Name=\"JobCards\" EntityType=\"LightSwitchApplication.JobCard\" /><Funct" +
                "ionImport Name=\"Query1\" ReturnType=\"Collection(LightSwitchApplication.JobCard)\" " +
                "EntitySet=\"JobCards\" m:HttpMethod=\"GET\" /><FunctionImport Name=\"Microsoft_LightS" +
                "witch_GetCanInformation\" ReturnType=\"Edm.String\" m:HttpMethod=\"GET\"><Parameter N" +
                "ame=\"dataServiceMembers\" Type=\"Edm.String\" Mode=\"In\" /></FunctionImport></Entity" +
                "Container></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.JobCard in the schema.
    /// </summary>
    /// <KeyProperties>
    /// JID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("JobCards")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("JID")]
    public partial class JobCard : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new JobCard object.
        /// </summary>
        /// <param name="jID">Initial value of JID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static JobCard CreateJobCard(int jID)
        {
            JobCard jobCard = new JobCard();
            jobCard.JID = jID;
            return jobCard;
        }
        /// <summary>
        /// There are no comments for Property JID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int JID
        {
            get
            {
                return this._JID;
            }
            set
            {
                this.OnJIDChanging(value);
                if (object.Equals(this.JID, value))
                {
                    return;
                }
                this._JID = value;
                this.OnJIDChanged();
                this.OnPropertyChanged("JID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _JID;
        partial void OnJIDChanging(int value);
        partial void OnJIDChanged();
        /// <summary>
        /// There are no comments for Property JobNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string JobNumber
        {
            get
            {
                return this._JobNumber;
            }
            set
            {
                this.OnJobNumberChanging(value);
                if (object.Equals(this.JobNumber, value))
                {
                    return;
                }
                this._JobNumber = value;
                this.OnJobNumberChanged();
                this.OnPropertyChanged("JobNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _JobNumber;
        partial void OnJobNumberChanging(string value);
        partial void OnJobNumberChanged();
        /// <summary>
        /// There are no comments for Property JName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string JName
        {
            get
            {
                return this._JName;
            }
            set
            {
                this.OnJNameChanging(value);
                if (object.Equals(this.JName, value))
                {
                    return;
                }
                this._JName = value;
                this.OnJNameChanged();
                this.OnPropertyChanged("JName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _JName;
        partial void OnJNameChanging(string value);
        partial void OnJNameChanged();
        /// <summary>
        /// There are no comments for Property BuildingOwner in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string BuildingOwner
        {
            get
            {
                return this._BuildingOwner;
            }
            set
            {
                this.OnBuildingOwnerChanging(value);
                if (object.Equals(this.BuildingOwner, value))
                {
                    return;
                }
                this._BuildingOwner = value;
                this.OnBuildingOwnerChanged();
                this.OnPropertyChanged("BuildingOwner");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _BuildingOwner;
        partial void OnBuildingOwnerChanging(string value);
        partial void OnBuildingOwnerChanged();
        /// <summary>
        /// There are no comments for Property GeneralContractor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string GeneralContractor
        {
            get
            {
                return this._GeneralContractor;
            }
            set
            {
                this.OnGeneralContractorChanging(value);
                if (object.Equals(this.GeneralContractor, value))
                {
                    return;
                }
                this._GeneralContractor = value;
                this.OnGeneralContractorChanged();
                this.OnPropertyChanged("GeneralContractor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _GeneralContractor;
        partial void OnGeneralContractorChanging(string value);
        partial void OnGeneralContractorChanged();
        /// <summary>
        /// There are no comments for Property JDescription in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string JDescription
        {
            get
            {
                return this._JDescription;
            }
            set
            {
                this.OnJDescriptionChanging(value);
                if (object.Equals(this.JDescription, value))
                {
                    return;
                }
                this._JDescription = value;
                this.OnJDescriptionChanged();
                this.OnPropertyChanged("JDescription");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _JDescription;
        partial void OnJDescriptionChanging(string value);
        partial void OnJDescriptionChanged();
        /// <summary>
        /// There are no comments for Property JHoursEstmated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> JHoursEstmated
        {
            get
            {
                return this._JHoursEstmated;
            }
            set
            {
                this.OnJHoursEstmatedChanging(value);
                if (object.Equals(this.JHoursEstmated, value))
                {
                    return;
                }
                this._JHoursEstmated = value;
                this.OnJHoursEstmatedChanged();
                this.OnPropertyChanged("JHoursEstmated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _JHoursEstmated;
        partial void OnJHoursEstmatedChanging(global::System.Nullable<decimal> value);
        partial void OnJHoursEstmatedChanged();
        /// <summary>
        /// There are no comments for Property JHoursTook in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> JHoursTook
        {
            get
            {
                return this._JHoursTook;
            }
            set
            {
                this.OnJHoursTookChanging(value);
                if (object.Equals(this.JHoursTook, value))
                {
                    return;
                }
                this._JHoursTook = value;
                this.OnJHoursTookChanged();
                this.OnPropertyChanged("JHoursTook");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _JHoursTook;
        partial void OnJHoursTookChanging(global::System.Nullable<decimal> value);
        partial void OnJHoursTookChanged();
        /// <summary>
        /// There are no comments for Property JPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> JPrice
        {
            get
            {
                return this._JPrice;
            }
            set
            {
                this.OnJPriceChanging(value);
                if (object.Equals(this.JPrice, value))
                {
                    return;
                }
                this._JPrice = value;
                this.OnJPriceChanged();
                this.OnPropertyChanged("JPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _JPrice;
        partial void OnJPriceChanging(global::System.Nullable<decimal> value);
        partial void OnJPriceChanged();
        /// <summary>
        /// There are no comments for Property JSquares in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> JSquares
        {
            get
            {
                return this._JSquares;
            }
            set
            {
                this.OnJSquaresChanging(value);
                if (object.Equals(this.JSquares, value))
                {
                    return;
                }
                this._JSquares = value;
                this.OnJSquaresChanged();
                this.OnPropertyChanged("JSquares");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _JSquares;
        partial void OnJSquaresChanging(global::System.Nullable<decimal> value);
        partial void OnJSquaresChanged();
        /// <summary>
        /// There are no comments for Property JDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> JDate
        {
            get
            {
                return this._JDate;
            }
            set
            {
                this.OnJDateChanging(value);
                if (object.Equals(this.JDate, value))
                {
                    return;
                }
                this._JDate = value;
                this.OnJDateChanged();
                this.OnPropertyChanged("JDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _JDate;
        partial void OnJDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnJDateChanged();
        /// <summary>
        /// There are no comments for Property JWarrenty in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string JWarrenty
        {
            get
            {
                return this._JWarrenty;
            }
            set
            {
                this.OnJWarrentyChanging(value);
                if (object.Equals(this.JWarrenty, value))
                {
                    return;
                }
                this._JWarrenty = value;
                this.OnJWarrentyChanged();
                this.OnPropertyChanged("JWarrenty");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _JWarrenty;
        partial void OnJWarrentyChanging(string value);
        partial void OnJWarrentyChanged();
        /// <summary>
        /// There are no comments for Property WarrantyNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string WarrantyNumber
        {
            get
            {
                return this._WarrantyNumber;
            }
            set
            {
                this.OnWarrantyNumberChanging(value);
                if (object.Equals(this.WarrantyNumber, value))
                {
                    return;
                }
                this._WarrantyNumber = value;
                this.OnWarrantyNumberChanged();
                this.OnPropertyChanged("WarrantyNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _WarrantyNumber;
        partial void OnWarrantyNumberChanging(string value);
        partial void OnWarrantyNumberChanged();
        /// <summary>
        /// There are no comments for Property WarrantyStart in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> WarrantyStart
        {
            get
            {
                return this._WarrantyStart;
            }
            set
            {
                this.OnWarrantyStartChanging(value);
                if (object.Equals(this.WarrantyStart, value))
                {
                    return;
                }
                this._WarrantyStart = value;
                this.OnWarrantyStartChanged();
                this.OnPropertyChanged("WarrantyStart");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _WarrantyStart;
        partial void OnWarrantyStartChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnWarrantyStartChanged();
        /// <summary>
        /// There are no comments for Property WarrantyEnd in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> WarrantyEnd
        {
            get
            {
                return this._WarrantyEnd;
            }
            set
            {
                this.OnWarrantyEndChanging(value);
                if (object.Equals(this.WarrantyEnd, value))
                {
                    return;
                }
                this._WarrantyEnd = value;
                this.OnWarrantyEndChanged();
                this.OnPropertyChanged("WarrantyEnd");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _WarrantyEnd;
        partial void OnWarrantyEndChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnWarrantyEndChanged();
        /// <summary>
        /// There are no comments for Property Address1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address1
        {
            get
            {
                return this._Address1;
            }
            set
            {
                this.OnAddress1Changing(value);
                if (object.Equals(this.Address1, value))
                {
                    return;
                }
                this._Address1 = value;
                this.OnAddress1Changed();
                this.OnPropertyChanged("Address1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address1;
        partial void OnAddress1Changing(string value);
        partial void OnAddress1Changed();
        /// <summary>
        /// There are no comments for Property Address2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address2
        {
            get
            {
                return this._Address2;
            }
            set
            {
                this.OnAddress2Changing(value);
                if (object.Equals(this.Address2, value))
                {
                    return;
                }
                this._Address2 = value;
                this.OnAddress2Changed();
                this.OnPropertyChanged("Address2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address2;
        partial void OnAddress2Changing(string value);
        partial void OnAddress2Changed();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                if (object.Equals(this.City, value))
                {
                    return;
                }
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                if (object.Equals(this.State, value))
                {
                    return;
                }
                this._State = value;
                this.OnStateChanged();
                this.OnPropertyChanged("State");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _State;
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property Zip in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Zip
        {
            get
            {
                return this._Zip;
            }
            set
            {
                this.OnZipChanging(value);
                if (object.Equals(this.Zip, value))
                {
                    return;
                }
                this._Zip = value;
                this.OnZipChanged();
                this.OnPropertyChanged("Zip");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Zip;
        partial void OnZipChanging(string value);
        partial void OnZipChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
