//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class CreateNewJobCard
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private CreateNewJobCard() : base("LightSwitchApplication.Job_System_11_30.DesktopClient:CreateNewJobCard")
        {
            global::LightSwitchApplication.CreateNewJobCard.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static CreateNewJobCard CreateInstance()
        {
            return new global::LightSwitchApplication.CreateNewJobCard(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewJobCard_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewJobCard_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewJobCard_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewJobCard_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewJobCard_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewJobCard_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreateNewJobCard_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void JobCardProperty_Changed();

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.JobCard JobCardProperty
        {
            get 
            {
                return global::LightSwitchApplication.CreateNewJobCard.DetailsClass.GetValue(this, global::LightSwitchApplication.CreateNewJobCard.DetailsClass.PropertySetProperties.JobCardProperty);
            }
            set
            {
                global::LightSwitchApplication.CreateNewJobCard.DetailsClass.SetValue(this, global::LightSwitchApplication.CreateNewJobCard.DetailsClass.PropertySetProperties.JobCardProperty, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCardProperty_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass, global::LightSwitchApplication.CreateNewJobCard.DetailsClass.PropertySet, global::LightSwitchApplication.CreateNewJobCard.DetailsClass.CommandSet, global::LightSwitchApplication.CreateNewJobCard.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.CreateNewJobCard.DetailsClass.PropertySetProperties.JobCardProperty;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass>.Entry
                __CreateNewJobCardEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass>.Entry(
                    global::LightSwitchApplication.CreateNewJobCard.DetailsClass.__CreateNewJobCard_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.CreateNewJobCard.DetailsClass.__CreateNewJobCard_InvokeSavingEvent,
                    global::LightSwitchApplication.CreateNewJobCard.DetailsClass.__CreateNewJobCard_InvokeSavedEvent,
                    global::LightSwitchApplication.CreateNewJobCard.DetailsClass.__CreateNewJobCard_InvokeClosingEvent,
                    global::LightSwitchApplication.CreateNewJobCard.DetailsClass.__CreateNewJobCard_InvokeCreated,
                    global::LightSwitchApplication.CreateNewJobCard.DetailsClass.__CreateNewJobCard_InvokeActivated,
                    global::LightSwitchApplication.CreateNewJobCard.DetailsClass.__CreateNewJobCard_InvokeSaveErrorEvent);
            private static void __CreateNewJobCard_InvokeInitializeDataWorkspace(global::LightSwitchApplication.CreateNewJobCard s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.CreateNewJobCard_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __CreateNewJobCard_InvokeSavingEvent(global::LightSwitchApplication.CreateNewJobCard s)
            {
                bool handled = false;
                s.CreateNewJobCard_Saving(ref handled);
                return handled;
            }
            private static void __CreateNewJobCard_InvokeSavedEvent(global::LightSwitchApplication.CreateNewJobCard s)
            {
                s.CreateNewJobCard_Saved();
            }
            private static bool __CreateNewJobCard_InvokeClosingEvent(global::LightSwitchApplication.CreateNewJobCard s)
            {
                bool cancel = false;
                s.CreateNewJobCard_Closing(ref cancel);
                return cancel;
            }
            private static void __CreateNewJobCard_InvokeCreated(global::LightSwitchApplication.CreateNewJobCard s)
            {
                s.CreateNewJobCard_Created();
            }
            private static void __CreateNewJobCard_InvokeActivated(global::LightSwitchApplication.CreateNewJobCard s)
            {
                s.CreateNewJobCard_Activated();
            }
            private static bool __CreateNewJobCard_InvokeSaveErrorEvent(global::LightSwitchApplication.CreateNewJobCard s, global::System.Exception ex)
            {
                bool handled = false;
                s.CreateNewJobCard_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.CreateNewJobCard.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.CreateNewJobCard.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.CreateNewJobCard.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass, global::LightSwitchApplication.JobCard>.Data _JobCardProperty;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass, global::LightSwitchApplication.JobCard> JobCardProperty
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass, global::LightSwitchApplication.JobCard>)base.GetItem(global::LightSwitchApplication.CreateNewJobCard.DetailsClass.PropertySetProperties.JobCardProperty);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass, global::LightSwitchApplication.JobCard>.Entry
                    JobCardProperty = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass, global::LightSwitchApplication.JobCard>.Entry(
                        "JobCardProperty",
                        false,
                        global::LightSwitchApplication.CreateNewJobCard.DetailsClass.PropertySetProperties._JobCardProperty_Stub,
                        global::LightSwitchApplication.CreateNewJobCard.DetailsClass.PropertySetProperties._JobCardProperty_Validate,
                        global::LightSwitchApplication.CreateNewJobCard.DetailsClass.PropertySetProperties._JobCardProperty_OnValueChanged);
                private static void _JobCardProperty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.CreateNewJobCard.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.CreateNewJobCard, global::LightSwitchApplication.CreateNewJobCard.DetailsClass, global::LightSwitchApplication.JobCard>.Data> c, global::LightSwitchApplication.CreateNewJobCard.DetailsClass d, object sf)
                {
                    c(d, ref d._JobCardProperty, sf);
                }
                private static void _JobCardProperty_Validate(global::LightSwitchApplication.CreateNewJobCard s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.JobCardProperty_Validate(r);
                }
                private static void _JobCardProperty_OnValueChanged(global::LightSwitchApplication.CreateNewJobCard s)
                {
                    s.JobCardProperty_Changed();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class SearchJobCards
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private SearchJobCards() : base("LightSwitchApplication.Job_System_11_30.DesktopClient:SearchJobCards")
        {
            global::LightSwitchApplication.SearchJobCards.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static SearchJobCards CreateInstance()
        {
            return new global::LightSwitchApplication.SearchJobCards(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchJobCards_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchJobCards_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchJobCards_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchJobCards_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchJobCards_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchJobCards_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchJobCards_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void JobCards_SelectionChanged();

        partial void JobCards_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_Loaded(bool succeeded);

        /// <summary>
        /// Gets the JobCards visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.JobCard> JobCards
        {
            get
            {
                return global::LightSwitchApplication.SearchJobCards.DetailsClass.GetValue(this, global::LightSwitchApplication.SearchJobCards.DetailsClass.PropertySetProperties.JobCards);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void JobCards_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Calls the MyOwnMethod screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void MyOwnMethod()
        {
            this.Details.Methods.MyOwnMethod.CreateInvocation().Execute();
        }
        partial void MyOwnMethod_CanExecute(ref bool result);
        partial void MyOwnMethod_Execute();

        /// <summary>
        /// Calls the Print screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Print()
        {
            this.Details.Methods.Print.CreateInvocation().Execute();
        }
        partial void Print_CanExecute(ref bool result);
        partial void Print_Execute();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass, global::LightSwitchApplication.SearchJobCards.DetailsClass.PropertySet, global::LightSwitchApplication.SearchJobCards.DetailsClass.CommandSet, global::LightSwitchApplication.SearchJobCards.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.SearchJobCards.DetailsClass.PropertySetProperties.JobCards;
                var initializeCommandEntry = global::LightSwitchApplication.SearchJobCards.DetailsClass.CommandSetProperties.MyOwnMethod;
                var initializeMethodEntry = global::LightSwitchApplication.SearchJobCards.DetailsClass.MethodSetProperties.MyOwnMethod;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Entry
                __SearchJobCardsEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Entry(
                    global::LightSwitchApplication.SearchJobCards.DetailsClass.__SearchJobCards_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.SearchJobCards.DetailsClass.__SearchJobCards_InvokeSavingEvent,
                    global::LightSwitchApplication.SearchJobCards.DetailsClass.__SearchJobCards_InvokeSavedEvent,
                    global::LightSwitchApplication.SearchJobCards.DetailsClass.__SearchJobCards_InvokeClosingEvent,
                    global::LightSwitchApplication.SearchJobCards.DetailsClass.__SearchJobCards_InvokeCreated,
                    global::LightSwitchApplication.SearchJobCards.DetailsClass.__SearchJobCards_InvokeActivated,
                    global::LightSwitchApplication.SearchJobCards.DetailsClass.__SearchJobCards_InvokeSaveErrorEvent);
            private static void __SearchJobCards_InvokeInitializeDataWorkspace(global::LightSwitchApplication.SearchJobCards s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.SearchJobCards_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __SearchJobCards_InvokeSavingEvent(global::LightSwitchApplication.SearchJobCards s)
            {
                bool handled = false;
                s.SearchJobCards_Saving(ref handled);
                return handled;
            }
            private static void __SearchJobCards_InvokeSavedEvent(global::LightSwitchApplication.SearchJobCards s)
            {
                s.SearchJobCards_Saved();
            }
            private static bool __SearchJobCards_InvokeClosingEvent(global::LightSwitchApplication.SearchJobCards s)
            {
                bool cancel = false;
                s.SearchJobCards_Closing(ref cancel);
                return cancel;
            }
            private static void __SearchJobCards_InvokeCreated(global::LightSwitchApplication.SearchJobCards s)
            {
                s.SearchJobCards_Created();
            }
            private static void __SearchJobCards_InvokeActivated(global::LightSwitchApplication.SearchJobCards s)
            {
                s.SearchJobCards_Activated();
            }
            private static bool __SearchJobCards_InvokeSaveErrorEvent(global::LightSwitchApplication.SearchJobCards s, global::System.Exception ex)
            {
                bool handled = false;
                s.SearchJobCards_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.SearchJobCards.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.SearchJobCards.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.SearchJobCards.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable JobCardsQuery()
            {
                return this.Screen.DataWorkspace.MRC_DataBaseData.JobCards;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass, global::LightSwitchApplication.JobCard>.Data _JobCards;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Data _MyOwnMethodCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Data _PrintCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Data _MyOwnMethodMethod;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Data _PrintMethod;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass, global::LightSwitchApplication.JobCard> JobCards
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass, global::LightSwitchApplication.JobCard>)base.GetItem(global::LightSwitchApplication.SearchJobCards.DetailsClass.PropertySetProperties.JobCards);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass> MyOwnMethod
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>)base.GetItem(global::LightSwitchApplication.SearchJobCards.DetailsClass.CommandSetProperties.MyOwnMethod);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass> Print
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>)base.GetItem(global::LightSwitchApplication.SearchJobCards.DetailsClass.CommandSetProperties.Print);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass> MyOwnMethod
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>)base.GetItem(global::LightSwitchApplication.SearchJobCards.DetailsClass.MethodSetProperties.MyOwnMethod);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass> Print
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>)base.GetItem(global::LightSwitchApplication.SearchJobCards.DetailsClass.MethodSetProperties.Print);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass, global::LightSwitchApplication.JobCard>.Entry
                    JobCards = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass, global::LightSwitchApplication.JobCard>.Entry(
                        "JobCards",
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.PropertySetProperties._JobCards_Stub,
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.PropertySetProperties._JobCards_Validate,
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.PropertySetProperties._JobCards_CreateQuery,
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.PropertySetProperties._JobCards_SelectionChanged,
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.PropertySetProperties._JobCards_OnCollectionChanged,
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.PropertySetProperties._JobCards_OnLoaded);
                private static void _JobCards_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchJobCards.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass, global::LightSwitchApplication.JobCard>.Data> c, global::LightSwitchApplication.SearchJobCards.DetailsClass d, object sf)
                {
                    c(d, ref d._JobCards, sf);
                }
                private static void _JobCards_Validate(global::LightSwitchApplication.SearchJobCards s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.JobCards_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _JobCards_CreateQuery(global::LightSwitchApplication.SearchJobCards.DetailsClass d, object[] args)
                {
                    return d.JobCardsQuery();
                }
                private static void _JobCards_SelectionChanged(global::LightSwitchApplication.SearchJobCards s)
                {
                    s.JobCards_SelectionChanged();
                }
                private static void _JobCards_OnCollectionChanged(global::LightSwitchApplication.SearchJobCards s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.JobCards_Changed(e);
                }
                private static void _JobCards_OnLoaded(global::LightSwitchApplication.SearchJobCards s, bool succeeded)
                {
                    s.JobCards_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Entry
                    MyOwnMethod = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Entry(
                        "MyOwnMethod",
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.CommandSetProperties._MyOwnMethod_Stub,
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.CommandSetProperties._MyOwnMethod_CreateExecutableObject);
                private static void _MyOwnMethod_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchJobCards.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Data> c, global::LightSwitchApplication.SearchJobCards.DetailsClass d, object sf)
                {
                    c(d, ref d._MyOwnMethodCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _MyOwnMethod_CreateExecutableObject(global::LightSwitchApplication.SearchJobCards.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.SearchJobCards.DetailsClass)d).Methods.MyOwnMethod.CreateInvocation();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Entry
                    Print = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Entry(
                        "Print",
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.CommandSetProperties._Print_Stub,
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.CommandSetProperties._Print_CreateExecutableObject);
                private static void _Print_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchJobCards.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Data> c, global::LightSwitchApplication.SearchJobCards.DetailsClass d, object sf)
                {
                    c(d, ref d._PrintCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _Print_CreateExecutableObject(global::LightSwitchApplication.SearchJobCards.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.SearchJobCards.DetailsClass)d).Methods.Print.CreateInvocation();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Entry
                    MyOwnMethod = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Entry(
                        "MyOwnMethod",
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.MethodSetProperties._MyOwnMethod_Stub,
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.MethodSetProperties._MyOwnMethod_CanInvoke,
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.MethodSetProperties._MyOwnMethod_InvokeMethod);
                private static void _MyOwnMethod_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchJobCards.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Data> c, global::LightSwitchApplication.SearchJobCards.DetailsClass d, object sf)
                {
                    c(d, ref d._MyOwnMethodMethod, sf);
                }
                private static global::System.Exception _MyOwnMethod_CanInvoke(global::LightSwitchApplication.SearchJobCards.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.MyOwnMethod_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _MyOwnMethod_InvokeMethod(global::LightSwitchApplication.SearchJobCards.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.MyOwnMethod_Execute();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Entry
                    Print = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Entry(
                        "Print",
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.MethodSetProperties._Print_Stub,
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.MethodSetProperties._Print_CanInvoke,
                        global::LightSwitchApplication.SearchJobCards.DetailsClass.MethodSetProperties._Print_InvokeMethod);
                private static void _Print_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchJobCards.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.SearchJobCards, global::LightSwitchApplication.SearchJobCards.DetailsClass>.Data> c, global::LightSwitchApplication.SearchJobCards.DetailsClass d, object sf)
                {
                    c(d, ref d._PrintMethod, sf);
                }
                private static global::System.Exception _Print_CanInvoke(global::LightSwitchApplication.SearchJobCards.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.Print_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _Print_InvokeMethod(global::LightSwitchApplication.SearchJobCards.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.Print_Execute();
                }

            }
        }
    }
}
